# Generated by Django 5.2.7 on 2025-10-28 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('library', 'Library'), ('museum', 'Museum'), ('bookstore', 'Bookstore or Book Café'), ('university', 'University or College'), ('science', 'Science or Knowledge Centre'), ('cultural', 'Cultural Institution'), ('heritage', 'Heritage or Literary Landmark')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='LiteraryPlace',
        ),
    ]
