# Generated by Django 5.2.7 on 2025-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_knowledgeplace_delete_literaryplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgeplace',
            old_name='geom',
            new_name='geometry',
        ),
        migrations.RemoveField(
            model_name='knowledgeplace',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='knowledgeplace',
            name='website',
        ),
        migrations.AlterField(
            model_name='knowledgeplace',
            name='category',
            field=models.CharField(choices=[('library', 'Library'), ('museum', 'Museum'), ('university', 'University or College'), ('heritage', 'Heritage or Literary Landmark')], max_length=50),
        ),
    ]
